name: Setup-node
Description: "Setup Node.js environment for building and deploying the Next.js site"

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "24"
        cache: "npm"
      
    - name: Install Dependencies
      shell: bash
      run: npm ci
